- name: sudo apt-get update
  shell: apt update
  become: yes
  tags: php

- name: Ensure PHP requirement is install
  package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - lsb-release
      - apt-transport-https
      - ca-certificates
      - vim
  become: yes
  tags: php

- name: Ensure PHP repo added
  apt_key:
    url: https://packages.sury.org/php/apt.gpg
    state: present
  become: yes
  tags: php

- name: Adding PHP repository
  shell: echo "deb https://packages.sury.org/php/ stretch main" | sudo tee /etc/apt/sources.list.d/php.list
  become: yes
  tags: php

- name: sudo apt-get update
  shell: apt update
  become: yes
  tags: php

- name: Ensure PHP dependences are install
  package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - php{{ PHP_VERSION }}
      - php{{ PHP_VERSION }}-bcmath
      - php{{ PHP_VERSION }}-bz2
      - php{{ PHP_VERSION }}-intl
      - php{{ PHP_VERSION }}-gd
      - php{{ PHP_VERSION }}-mbstring
      - php{{ PHP_VERSION }}-mysql
      - php{{ PHP_VERSION }}-zip
      - php{{ PHP_VERSION }}-fpm
  become: yes
  tags: php
